#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations

i=1
while [ $i -lt 101 ]
do
    if [ $((i%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((i%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    i=$(( i + 1))
done
