#!/usr/bin/env bash
#The file /etc/passwd has already been covered in a previous project and you should be familiar with it. Today we will make up a story based on it.

awk '{print $1, $9}' apache-access.log
