#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

Hour=0
while [ $Hour -lt 13 ]
do
    echo "Hour: $Hour"
    MIN=1
    while [ $MIN -lt 60 ]
    do
        echo $MIN
        MIN=$(( MIN + 1 ))
    done
       Hour=$((Hour + 1))
done
